In [101]:
import matplotlib.pyplot as plt
import numpy as np
from qutip import *

vac = basis(5,0)
print(vac)


Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [102]:
a = destroy(5)

In [103]:

print(a.dag() * vac ) 

ket = basis(5,2)
print(ket)



Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]


In [104]:
n = num(5)
print(n*ket)


ket2 = (basis(5,0)+ basis(5,1)).unit()
print(ket2)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]]
Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]]


In [105]:
vac3 = basis(5,0)
d = displace(5, 1j)
s= squeeze(5, complex(0.25,0.25))
print(d*vac3)


Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.60655682+0.j        ]
 [ 0.        +0.60628133j]
 [-0.4303874 +0.j        ]
 [ 0.        -0.24104351j]
 [ 0.14552147+0.j        ]]


In [106]:
ket = basis(5,2)
print(ket*ket.dag())

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [107]:
k = (ket2dm(basis(5,4))+ket2dm(basis(5,2))).unit()
print(k)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5]]


In [111]:
x = coherent_dm(5, 1.25)
y = coherent_dm(5, complex(0,1.25))
np.testing.assert_almost_equal(tracedist(y,x),np.sqrt(1-fidelity(y,x)**2))


In [117]:
spin = basis(2,0)
vac = basis(2,0)

c = create(2)

print(c*vac)

print(sigmaz())

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]


In [123]:
vac = basis(5,0)
one = basis(5,1)
c = create(5)
N = num(5)
np.testing.assert_almost_equal(expect(N, vac),0)
np.testing.assert_almost_equal(expect(N, one),1)
coh = coherent_dm(5, 1j)
np.testing.assert_almost_equal(expect(N, coh),0.997055574580659)
cat = (basis(5,4) + 1j*basis(5,3)).unit()
np.testing.assert_almost_equal(expect(c,cat),0.99999999999998j)

In [125]:
states = [(c**k*vac).unit() for k in range(5)]
print(expect(N,states))

[0. 1. 2. 3. 4.]


In [129]:
cat_list = [(basis(5,4)+x*basis(5,3)).unit() for x in [0, 1j, -1, -1j] ]
print(expect(c,cat_list))

[ 0.+0.j  0.+1.j -1.+0.j  0.-1.j]


In [141]:
up = basis(2,0)
down = basis(2,1)
np.testing.assert_almost_equal(expect(sigmaz(),up),1)

spin1 = basis(2,0)
spin2 = basis(2,1)

two_spin = tensor(spin1,spin2)
sz1 = tensor(sigmaz(),qeye(2))
sz2 = tensor(qeye(2),sigmaz())
print(sz1,sz2)


Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0. -1.]] Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]


In [143]:
psi = basis(2,0)
rho = ket2dm(psi)
print(psi,rho)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]] Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 0.]]


In [147]:
X = sigmax()

S = spre(X)*spost(X.dag())

print(S)

Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [152]:
N = 5 
omega_a = 1
omega_c = 1.25
g = 0.05

a = tensor(identity(2),destroy(N))
sm = tensor(destroy(2), identity(N))
sz = tensor(sigmaz(), identity(N))

H= 0.5*omega_a*sz + omega_c*a.dag()*a + g*(a.dag()*sm+a*sm.dag())
print(H)

Quantum object: dims = [[2, 5], [2, 5]], shape = (10, 10), type = oper, isherm = True
Qobj data =
[[ 0.5         0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          1.75        0.          0.          0.          0.05
   0.          0.          0.          0.        ]
 [ 0.          0.          3.          0.          0.          0.
   0.07071068  0.          0.          0.        ]
 [ 0.          0.          0.          4.25        0.          0.
   0.          0.08660254  0.          0.        ]
 [ 0.          0.          0.          0.          5.5         0.
   0.          0.          0.1         0.        ]
 [ 0.          0.05        0.          0.          0.         -0.5
   0.          0.          0.          0.        ]
 [ 0.          0.          0.07071068  0.          0.          0.
   0.75        0.          0.          0.        ]
 [ 0.          0.          0.          0.08660254  0.          0.
   0.         

In [153]:
print(result)

NameError: name 'result' is not defined